package org.unrwa.yarmoukfield;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.ClipData;
import android.content.Context;
import android.content.Intent;
import android.content.pm.ResolveInfo;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.print.PrintAttributes;
import android.print.PrintManager;
import android.provider.MediaStore;
import android.provider.Settings;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.BaseAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ScrollView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import org.json.JSONObject;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class MainActivity extends Activity {
    private static final int NAV_HOME=0,NAV_PEOPLE=1,NAV_ROUTE=2,NAV_GUIDE=3,NAV_SETTINGS=4;
    private static final int REQUEST_IMPORT=4101,REQUEST_BACKUP=4102,REQUEST_PHOTO_ROOT=4103,REQUEST_CAPTURE_PHOTO=4104,REQUEST_HOUSE_PLAN=4105;
    private static final int NAVY=0xff123B5D,BLUE=0xff009ED2,SURFACE=0xffF4F8FB,TEXT=0xff15364D,MUTED=0xff667A89;
    private static final String APP_VERSION="1.5.0";
    private static final String DESIGNER_CREDIT="تصميم وتطوير التطبيق: المهندس محمد أمين عودة";
    private static final String ACKNOWLEDGEMENT="شكر وتقدير للمهندس عبد المالك أبو حرب والمهندس محمد عبد العال على دعمهما وتعاونهما في تطوير العمل الميداني";
    private static final String PRINT_CREDIT=DESIGNER_CREDIT;
    // Pages in the divided PDF are West 1-3, East 1-3, then Orouba/Taqaddum/Maalia.
    // The app sector order alternates East/West, therefore an explicit map is required.
    private static final int[] SECTOR_PDF_PAGES={3,0,4,1,5,2,6};
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private AppDatabase db;private AddressClassifier classifier;private BeneficiaryPhotoManager photoManager;private List<QuantityCatalog.Item> quantityCatalog;private LinearLayout root,header,bottom;private FrameLayout content;
    private Spinner projectSpinner;private TextView projectCaption;private String currentProject;private long currentProjectId;private int activePage=NAV_HOME;
    private String pendingBackup,pendingPhotoPhase="",pendingPhotoFileName="";private Uri pendingPhotoUri;private long pendingPhotoBeneficiaryId,pendingPhotoCapturedAt,deferredPhotoBeneficiaryId,pendingPlanBeneficiaryId;private String deferredPhotoPhase="";private AlertDialog beneficiaryDialog;

    @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(0xff0B273C);getWindow().setNavigationBarColor(0xff0B273C);
        getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);db=new AppDatabase(this);photoManager=new BeneficiaryPhotoManager(this);restorePendingPhoto();try{classifier=new AddressClassifier(this);quantityCatalog=QuantityCatalog.load(this);}catch(Exception e){fatal("تعذر تحميل المراجع الميدانية",e);return;}
        currentProject=getPreferences(MODE_PRIVATE).getString("current_project",AppDatabase.DEFAULT_PROJECT);currentProjectId=db.ensureProject(currentProject);buildShell();refreshProjects();showPage(NAV_HOME);}
    @Override protected void onDestroy(){worker.shutdownNow();if(db!=null)db.close();super.onDestroy();}

    private void buildShell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(SURFACE);setContentView(root);
        header=new LinearLayout(this);header.setOrientation(LinearLayout.VERTICAL);header.setPadding(dp(14),dp(8),dp(14),dp(10));header.setBackgroundColor(NAVY);root.addView(header,new LinearLayout.LayoutParams(-1,dp(188)));

        LinearLayout identity=new LinearLayout(this);identity.setGravity(Gravity.CENTER_VERTICAL);header.addView(identity,new LinearLayout.LayoutParams(-1,dp(116)));
        ImageView logo=new ImageView(this);logo.setImageResource(getResources().getIdentifier("unrwa_logo","drawable",getPackageName()));logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);identity.addView(logo,new LinearLayout.LayoutParams(dp(104),dp(104)));
        LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.setGravity(Gravity.CENTER_VERTICAL);titles.setPadding(dp(10),0,dp(6),0);identity.addView(titles,new LinearLayout.LayoutParams(0,-1,1));
        TextView title=text("مشروع المأوى في مخيم اليرموك",19,Color.WHITE,true);title.setMaxLines(2);titles.addView(title);
        titles.addView(text("وكالة غوث وتشغيل اللاجئين الفلسطينيين في سوريا",9,0xffD7EDF5,false));
        projectCaption=text("إصدار ميداني لأندرويد • "+APP_VERSION,9,0xffC8EAF5,true);titles.addView(projectCaption);
        TextView designer=text(DESIGNER_CREDIT,9,Color.WHITE,true);designer.setMaxLines(1);titles.addView(designer);
        TextView thanks=text("شكر وتقدير: م. عبد المالك أبو حرب • م. محمد عبد العال",7,0xffD7EDF5,false);thanks.setMaxLines(1);titles.addView(thanks);

        LinearLayout projectBox=new LinearLayout(this);projectBox.setGravity(Gravity.CENTER_VERTICAL);header.addView(projectBox,new LinearLayout.LayoutParams(-1,dp(52)));
        TextView label=text("المشروع الحالي",11,0xffD7EDF5,true);projectBox.addView(label,new LinearLayout.LayoutParams(dp(105),-1));
        projectSpinner=new Spinner(this);projectSpinner.setBackground(round(0xffF2F7FA,12,0,0));projectBox.addView(projectSpinner,new LinearLayout.LayoutParams(0,dp(46),1));
        content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));bottom=new LinearLayout(this);bottom.setGravity(Gravity.CENTER);bottom.setPadding(dp(5),dp(5),dp(5),dp(5));bottom.setBackgroundColor(Color.WHITE);root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(70)));
        String[]names={"⌂\nالرئيسية","⌕\nالدراسات","✓\nالمتابعة","⌖\nالدليل","⚙\nالإعدادات"};for(int i=0;i<names.length;i++){final int page=i;Button b=new Button(this);b.setText(names[i]);b.setTextSize(11);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setPadding(0,0,0,0);b.setTag(i);b.setOnClickListener(v->showPage(page));bottom.addView(b,new LinearLayout.LayoutParams(0,-1,1));}}

    private void refreshProjects(){List<String>names=db.listProjects();ArrayAdapter<String>adapter=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names){@Override public View getView(int p,View c,ViewGroup parent){TextView v=(TextView)super.getView(p,c,parent);v.setTextColor(NAVY);v.setGravity(Gravity.CENTER);v.setTextSize(12);return v;}};projectSpinner.setAdapter(adapter);int selected=Math.max(0,names.indexOf(currentProject));projectSpinner.setSelection(selected,false);
        projectSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){boolean ready;@Override public void onNothingSelected(AdapterView<?>p){}@Override public void onItemSelected(AdapterView<?>p,View v,int pos,long id){if(!ready){ready=true;return;}currentProject=String.valueOf(p.getItemAtPosition(pos));currentProjectId=db.projectId(currentProject);getPreferences(MODE_PRIVATE).edit().putString("current_project",currentProject).apply();renderActive();}});}

    private void showPage(int page){activePage=page;renderActive();for(int i=0;i<bottom.getChildCount();i++){Button b=(Button)bottom.getChildAt(i);boolean active=(Integer)b.getTag()==page;b.setTextColor(active?Color.WHITE:MUTED);b.setTypeface(null,active?Typeface.BOLD:Typeface.NORMAL);b.setBackground(active?round(BLUE,14,0,0):round(Color.TRANSPARENT,14,0,0));}}
    private void renderActive(){content.removeAllViews();if(activePage==NAV_HOME)showHome();else if(activePage==NAV_PEOPLE)showPeople(false);else if(activePage==NAV_ROUTE)showPeople(true);else if(activePage==NAV_GUIDE)showGuide();else showSettings();}

    private void showHome(){FrameLayout frame=new FrameLayout(this);content.addView(frame,new FrameLayout.LayoutParams(-1,-1));ImageView mark=new ImageView(this);mark.setImageResource(computeResource("ic_watermark","drawable"));mark.setAlpha(.055f);mark.setScaleType(ImageView.ScaleType.CENTER_INSIDE);FrameLayout.LayoutParams mp=new FrameLayout.LayoutParams(dp(340),dp(340),Gravity.CENTER);frame.addView(mark,mp);
        ScrollView scroll=new ScrollView(this);frame.addView(scroll,new FrameLayout.LayoutParams(-1,-1));LinearLayout box=column(dp(16));scroll.addView(box,new ScrollView.LayoutParams(-1,-2));
        TextView greeting=text("مرحباً بك في مركز العمل الميداني",22,NAVY,true);box.addView(greeting);TextView subtitle=text("قائمة مرتبة، عناوين أوضح، ومتابعة ميدانية أسرع — تعمل دون إنترنت",13,MUTED,false);subtitle.setPadding(0,dp(4),0,dp(14));box.addView(subtitle);
        LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);box.addView(stats,new LinearLayout.LayoutParams(-1,-2));stats.addView(stat("الدراسات",db.stageCount(currentProjectId,"study"),NAVY),new LinearLayout.LayoutParams(0,dp(108),1));stats.addView(stat("جاهزة للدفعة",db.studyReadyCount(currentProjectId),0xffC9851C),new LinearLayout.LayoutParams(0,dp(108),1));
        LinearLayout stats2=new LinearLayout(this);stats2.setOrientation(LinearLayout.HORIZONTAL);box.addView(stats2,new LinearLayout.LayoutParams(-1,-2));stats2.addView(stat("قيد المتابعة",db.stageCount(currentProjectId,"followup"),0xff0E7490),new LinearLayout.LayoutParams(0,dp(108),1));stats2.addView(stat("منجزة",db.followupCompletedCount(currentProjectId),0xff149176),new LinearLayout.LayoutParams(0,dp(108),1));
        TextView actionsTitle=text("إجراءات سريعة",17,NAVY,true);actionsTitle.setPadding(0,dp(18),0,dp(8));box.addView(actionsTitle);
        box.addView(action("بدء دراسة مستفيد جديد","إضافة الاسم والعنوان وتصوير الأضرار قبل الترميم",0xff7A5CB8,v->showAddBeneficiary()));
        box.addView(action("فتح الدراسات","استكمال المخطط والكميات والمبلغ وتجهيز الاعتماد",BLUE,v->showPage(NAV_PEOPLE)));
        box.addView(action("متابعة قائمة التنفيذ","التصوير أثناء الترميم وبعده للقوائم المعتمدة",0xff149176,v->showPage(NAV_ROUTE)));
        box.addView(action("استيراد قائمة متابعة","Excel / CSV / JSON مع إصلاح قارئ XML",0xff0E7490,v->chooseImport()));
        box.addView(action("دليل قطاعات مخيم اليرموك","المخطط المرجعي والشوارع داخل كل قطاع",NAVY,v->showPage(NAV_GUIDE)));
        box.addView(action("دليل استخدام التطبيق","شرح مختصر للاستيراد والترتيب والزيارات والنسخ الاحتياطي",0xff7A5CB8,v->showUserGuide()));
    }

    private View stat(String label,int value,int color){LinearLayout card=column(dp(12));card.setGravity(Gravity.CENTER);card.setBackground(round(Color.WHITE,18,0xffDCE9EF,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(108),1);p.setMargins(dp(5),dp(5),dp(5),dp(5));card.setLayoutParams(p);TextView number=text(String.valueOf(value),28,color,true);number.setGravity(Gravity.CENTER);card.addView(number);TextView caption=text(label,12,MUTED,true);caption.setGravity(Gravity.CENTER);card.addView(caption);return card;}
    private View action(String title,String subtitle,int color,View.OnClickListener click){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(16),dp(12),dp(16),dp(12));card.setBackground(round(Color.WHITE,18,0xffDCE9EF,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(82));p.setMargins(0,dp(5),0,dp(5));card.setLayoutParams(p);TextView icon=text("←",24,color,true);icon.setGravity(Gravity.CENTER);card.addView(icon,new LinearLayout.LayoutParams(dp(44),-1));LinearLayout labels=column(0);labels.addView(text(title,15,NAVY,true));labels.addView(text(subtitle,11,MUTED,false));card.addView(labels,new LinearLayout.LayoutParams(0,-2,1));card.setOnClickListener(click);return card;}

    private void showPeople(boolean followup){LinearLayout page=column(dp(12));content.addView(page,new FrameLayout.LayoutParams(-1,-1));LinearLayout titleRow=new LinearLayout(this);titleRow.setGravity(Gravity.CENTER_VERTICAL);page.addView(titleRow,new LinearLayout.LayoutParams(-1,dp(55)));titleRow.addView(text(followup?"متابعة التنفيذ":"الدراسات",21,NAVY,true),new LinearLayout.LayoutParams(0,-2,1));
        if(followup){Button print=smallButton("طباعة A4",NAVY);print.setOnClickListener(v->printRoute());titleRow.addView(print);}else{Button manual=smallButton("+ دراسة",0xff7A5CB8);manual.setOnClickListener(v->showAddBeneficiary());titleRow.addView(manual);Button batch=smallButton("دفعة 50",BLUE);batch.setOnClickListener(v->promoteReadyBatch());titleRow.addView(batch);}
        EditText search=new EditText(this);search.setHint("ابحث بالاسم أو العنوان أو الهاتف أو رقم التسجيل");search.setSingleLine(true);search.setTextSize(14);search.setPadding(dp(14),0,dp(14),0);search.setBackground(round(Color.WHITE,14,0xffD6E5EB,1));page.addView(search,new LinearLayout.LayoutParams(-1,dp(50)));
        LinearLayout filterRow=new LinearLayout(this);filterRow.setGravity(Gravity.CENTER_VERTICAL);filterRow.setPadding(0,dp(6),0,dp(6));page.addView(filterRow,new LinearLayout.LayoutParams(-1,dp(54)));TextView hint=text(followup?"مرتب حسب القطاع والشارع والجادة":"حالة تجهيز الدراسة",12,MUTED,true);filterRow.addView(hint,new LinearLayout.LayoutParams(0,-2,1));Spinner filter=new Spinner(this);String[]filterNames=followup?new String[]{"غير المنجز","الكل","تمت الزيارة","بحاجة لمراجعة"}:new String[]{"الكل","قيد الدراسة","جاهزة للدفعة"};String[]filterValues=followup?new String[]{"pending","all","completed","review"}:new String[]{"all","draft","ready"};ArrayAdapter<String>fa=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,filterNames);filter.setAdapter(fa);filter.setBackground(round(Color.WHITE,12,0xffD6E5EB,1));filterRow.addView(filter,new LinearLayout.LayoutParams(dp(150),dp(44)));
        FrameLayout listBox=new FrameLayout(this);page.addView(listBox,new LinearLayout.LayoutParams(-1,0,1));ListView list=new ListView(this);list.setDividerHeight(dp(7));list.setDivider(new android.graphics.drawable.ColorDrawable(SURFACE));list.setPadding(0,dp(3),0,dp(12));list.setClipToPadding(false);listBox.addView(list,new FrameLayout.LayoutParams(-1,-1));TextView empty=text(followup?"لا توجد أسماء في المتابعة ضمن هذا الفلتر":"لا توجد دراسات",16,MUTED,true);empty.setGravity(Gravity.CENTER);listBox.addView(empty,new FrameLayout.LayoutParams(-1,-1));list.setEmptyView(empty);
        Runnable refresh=()->{String state=filterValues[filter.getSelectedItemPosition()];List<AppDatabase.Beneficiary>rows=db.listStage(currentProjectId,search.getText().toString(),followup?"followup":"study",state);list.setAdapter(new BeneficiaryAdapter(rows,followup));};
        filter.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){@Override public void onNothingSelected(AdapterView<?>p){}@Override public void onItemSelected(AdapterView<?>p,View v,int pos,long id){refresh.run();}});search.addTextChangedListener(new TextWatcher(){@Override public void beforeTextChanged(CharSequence s,int st,int c,int a){}@Override public void onTextChanged(CharSequence s,int st,int b,int c){refresh.run();}@Override public void afterTextChanged(Editable e){}});refresh.run();}

    private final class BeneficiaryAdapter extends BaseAdapter{private final List<AppDatabase.Beneficiary>rows;private final boolean followup;BeneficiaryAdapter(List<AppDatabase.Beneficiary>r,boolean field){rows=r;followup=field;}@Override public int getCount(){return rows.size();}@Override public Object getItem(int p){return rows.get(p);}@Override public long getItemId(int p){return rows.get(p).id;}
        @Override public View getView(int position,View convert,ViewGroup parent){AppDatabase.Beneficiary b=rows.get(position);String stateValue=followup?b.visitStatus:b.studyStatus;int stateColor=followup?statusColor(stateValue):studyStatusColor(stateValue);LinearLayout card=column(dp(13));card.setBackground(round(Color.WHITE,16,stateColor,2));card.setMinimumHeight(dp(118));TextView name=text((followup?(position+1)+". ":"")+safe(b.name,"مستفيد بلا اسم"),16,NAVY,true);card.addView(name);TextView sector=text(b.sector+(b.street.isEmpty()?"":" — "+shortStreet(b.street)),12,0xff0E7490,true);sector.setPadding(0,dp(4),0,0);card.addView(sector);TextView addr=text(safe(b.address,"العنوان بحاجة لاستكمال"),13,TEXT,false);addr.setMaxLines(2);card.addView(addr);String detail=(b.phone1.isEmpty()?"":"☎ "+b.phone1)+(b.phone2.isEmpty()?"":"  |  "+b.phone2)+(b.amount.isEmpty()?"":"     المبلغ: "+b.amount)+(followup?"     الإنجاز: "+b.progressPercent+"%":"");TextView d=text(detail,11,MUTED,false);d.setPadding(0,dp(4),0,0);card.addView(d);TextView state=text(followup?statusLabel(stateValue):studyStatusLabel(stateValue),10,stateColor,true);state.setGravity(Gravity.END);card.addView(state);card.setOnClickListener(v->showBeneficiary(b));return card;}}

    private void showAddBeneficiary(){ScrollView scroll=new ScrollView(this);LinearLayout form=column(dp(18));scroll.addView(form);form.addView(text("بدء دراسة مستفيد جديد",21,NAVY,true));TextView intro=text("لا تحتاج إلى قائمة مسبقة. احفظ الاسم والبيانات الأولية، ثم افتح الدراسة لتصوير الأضرار واستكمال العنوان والمخطط والكميات.",12,MUTED,false);intro.setPadding(0,dp(4),0,dp(8));form.addView(intro);
        EditText name=formInput(form,"اسم المستفيد *","الاسم الثلاثي",InputType.TYPE_CLASS_TEXT,false);EditText registration=formInput(form,"رقم التسجيل","اختياري",InputType.TYPE_CLASS_TEXT,false);EditText phone=formInput(form,"رقم الهاتف","اختياري",InputType.TYPE_CLASS_PHONE,false);EditText address=formInput(form,"العنوان","يساعد في تحديد القطاع والمسار",InputType.TYPE_CLASS_TEXT,true);EditText notes=formInput(form,"ملاحظات الدراسة الأولية","وصف حالة المنزل أو أي ملاحظة ميدانية",InputType.TYPE_CLASS_TEXT,true);
        AlertDialog dialog=new AlertDialog.Builder(this).setView(scroll).setPositiveButton("حفظ المستفيد",null).setNegativeButton("إلغاء",null).create();dialog.setOnShowListener(v->{dialog.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.96),(int)(getResources().getDisplayMetrics().heightPixels*.92));dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(button->{String cleanName=name.getText().toString().trim();if(cleanName.isEmpty()){name.setError("اسم المستفيد مطلوب");return;}try{AppDatabase.Beneficiary b=new AppDatabase.Beneficiary();b.name=cleanName;b.registration=registration.getText().toString().trim();b.phone1=phone.getText().toString().trim();b.address=address.getText().toString().trim();b.notes=notes.getText().toString().trim();if(b.address.isEmpty()){b.matchStatus="أضيف يدوياً — العنوان بحاجة لمراجعة";}else{AddressClassifier.Match match=classifier.classify(b.address);b.sector=match.sector;b.street=match.street;b.matchStatus="أضيف يدوياً | "+match.review;b.confidence=match.confidence;b.sectorOrder=match.sectorIndex;b.routeOrder=match.routeIndex;b.streetOrder=match.streetIndex;b.alleyOrder=match.alleyIndex;}db.addBeneficiary(currentProjectId,b);dialog.dismiss();showPage(NAV_PEOPLE);showBeneficiary(b);toast("تمت إضافة المستفيد ويمكن بدء التصوير");}catch(Exception error){new AlertDialog.Builder(this).setTitle("تعذر حفظ المستفيد").setMessage(error.getMessage()).setPositiveButton("حسناً",null).show();}});});dialog.show();}
    private EditText formInput(LinearLayout form,String label,String hint,int type,boolean multiline){TextView caption=text(label,12,NAVY,true);caption.setPadding(0,dp(8),0,dp(4));form.addView(caption);EditText input=new EditText(this);input.setHint(hint);input.setInputType(type|(multiline?InputType.TYPE_TEXT_FLAG_MULTI_LINE:0));input.setSingleLine(!multiline);if(multiline){input.setMinLines(2);input.setGravity(Gravity.TOP|Gravity.START);}input.setTextSize(14);input.setPadding(dp(12),dp(8),dp(12),dp(8));input.setBackground(round(0xffF4F8FB,12,0xffD6E5EB,1));form.addView(input,new LinearLayout.LayoutParams(-1,multiline?dp(82):dp(50)));return input;}

    private void showBeneficiary(AppDatabase.Beneficiary b){boolean study="study".equals(b.workflowStage);ScrollView scroll=new ScrollView(this);LinearLayout box=column(dp(18));scroll.addView(box);box.addView(text(safe(b.name,"مستفيد بلا اسم"),21,NAVY,true));TextView stage=text(study?"مرحلة الدراسة — "+studyStatusLabel(b.studyStatus):"مرحلة متابعة التنفيذ"+(b.followupBatch.isEmpty()?"":" — "+b.followupBatch),12,study?0xff7A5CB8:0xff149176,true);stage.setPadding(0,dp(3),0,dp(8));box.addView(stage);
        box.addView(info("القطاع",b.sector));box.addView(info("الشارع المرجعي",b.street));box.addView(info("الهاتف",b.phone1));box.addView(info("الهاتف الثاني",b.phone2));box.addView(info("رقم التسجيل",b.registration));
        AlertDialog dialog=new AlertDialog.Builder(this).setView(scroll).setNegativeButton("إغلاق",null).create();beneficiaryDialog=dialog;
        if(study)buildStudyDetails(box,b,dialog);else buildFollowupDetails(box,b,dialog);
        LinearLayout calls=new LinearLayout(this);calls.setGravity(Gravity.CENTER);box.addView(calls);if(!b.phone1.isEmpty())calls.addView(dialogButton("اتصال 1",BLUE,v->dial(b.phone1)));if(!b.phone2.isEmpty())calls.addView(dialogButton("اتصال 2",BLUE,v->dial(b.phone2)));
        dialog.setOnDismissListener(v->{if(beneficiaryDialog==dialog)beneficiaryDialog=null;});dialog.setOnShowListener(x->{dialog.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94),(int)(getResources().getDisplayMetrics().heightPixels*.94));});dialog.show();}

    private void buildStudyDetails(LinearLayout box,AppDatabase.Beneficiary b,AlertDialog dialog){
        TextView studyTitle=text("بيانات دراسة المنزل",17,NAVY,true);studyTitle.setPadding(0,dp(8),0,0);box.addView(studyTitle);
        EditText address=formInput(box,"العنوان التفصيلي *","القطاع، الشارع، الجادة، الزقاق، رقم المنزل وأقرب معلم",InputType.TYPE_CLASS_TEXT,true);address.setText(b.address);
        EditText damage=formInput(box,"وصف الأضرار *","الغرف والأسقف والجدران والأبواب والنوافذ والأعمال المطلوبة",InputType.TYPE_CLASS_TEXT,true);damage.setText(b.damageNotes);
        TextView quantitiesTitle=text("جدول الكميات المرجعي *",12,NAVY,true);quantitiesTitle.setPadding(0,dp(10),0,dp(4));box.addView(quantitiesTitle);
        LinearLayout quantityCard=column(dp(12));quantityCard.setBackground(round(0xffF4F8FB,12,0xffD6E5EB,1));box.addView(quantityCard,new LinearLayout.LayoutParams(-1,-2));
        TextView quantitySummary=text(quantitySummary(b.id),13,TEXT,true);quantityCard.addView(quantitySummary);
        TextView amountSummary=text(paymentSummary(db.quantityTotal(b.id)),12,0xff0E7490,true);amountSummary.setPadding(0,dp(5),0,dp(4));quantityCard.addView(amountSummary);
        Button editQuantities=smallButton(db.quantityCount(b.id)==0?"تعبئة جدول الكميات (37 بنداً)":"تعديل جدول الكميات",0xff7A5CB8);quantityCard.addView(editQuantities,new LinearLayout.LayoutParams(-1,dp(48)));
        Runnable refreshQuantitySummary=()->{int count=db.quantityCount(b.id);quantitySummary.setText(quantitySummary(b.id));amountSummary.setText(paymentSummary(db.quantityTotal(b.id)));editQuantities.setText(count==0?"تعبئة جدول الكميات (37 بنداً)":"تعديل جدول الكميات");};
        editQuantities.setOnClickListener(v->showQuantityEditor(b,true,refreshQuantitySummary));
        LinearLayout planActions=new LinearLayout(this);planActions.setGravity(Gravity.CENTER);Button attach=dialogButton(b.drawingUri.isEmpty()?"إرفاق مخطط المنزل":"تغيير مخطط المنزل",0xff7A5CB8,v->chooseHousePlan(b));planActions.addView(attach);Button open=dialogButton("فتح المخطط",NAVY,v->openHousePlan(b.drawingUri));open.setEnabled(!b.drawingUri.isEmpty());open.setAlpha(b.drawingUri.isEmpty()?.4f:1f);planActions.addView(open);box.addView(planActions);box.addView(text(b.drawingUri.isEmpty()?"لم يُرفق مخطط بعد — يقبل PDF أو DXF أو DWG أو صورة":"تم ربط ملف مخطط المنزل بالسجل",11,b.drawingUri.isEmpty()?0xffC9851C:0xff149176,true));
        TextView photosTitle=text("صور الأضرار وقبل الترميم",17,NAVY,true);photosTitle.setPadding(0,dp(14),0,dp(5));box.addView(photosTitle);box.addView(text(photoManager.isConfigured()?"الحفظ داخل: "+photoManager.rootName():"اختر مجلد الصور عند التقاط أول صورة",11,photoManager.isConfigured()?0xff149176:0xffC9851C,true));box.addView(photoStageCard(b,BeneficiaryPhotoManager.BEFORE,0xff0E7490,true));
        Button save=smallButton("حفظ بيانات الدراسة",0xff0E7490);save.setOnClickListener(v->{saveStudy(b,address,damage);dialog.dismiss();renderActive();toast("تم حفظ بيانات الدراسة");});LinearLayout.LayoutParams saveParams=new LinearLayout.LayoutParams(-1,dp(50));saveParams.setMargins(0,dp(10),0,0);box.addView(save,saveParams);
        Button ready=smallButton("اعتماد الدراسة وتجهيزها لدفعة 50",0xff149176);ready.setOnClickListener(v->markStudyReady(b,address,damage,dialog));LinearLayout.LayoutParams readyParams=new LinearLayout.LayoutParams(-1,dp(50));readyParams.setMargins(0,dp(6),0,dp(8));box.addView(ready,readyParams);
    }

    private void buildFollowupDetails(LinearLayout box,AppDatabase.Beneficiary b,AlertDialog dialog){double total=db.quantityTotal(b.id);box.addView(info("العنوان التفصيلي",b.address));box.addView(info("الإجمالي المعتمد",total>0?QuantityCatalog.money(total)+" $":b.amount));box.addView(info("الدفعة الأولى 60%",total>0?QuantityCatalog.money(total*QuantityCatalog.FIRST_PAYMENT_RATIO)+" $":"—"));box.addView(info("الدفعة الثانية 40%",total>0?QuantityCatalog.money(total*QuantityCatalog.SECOND_PAYMENT_RATIO)+" $":"—"));box.addView(info("وصف الأضرار",b.damageNotes));box.addView(info("جدول الكميات",quantitySummary(b.id)));if(db.quantityCount(b.id)>0){Button boq=smallButton("عرض جدول الكميات المعتمد",0xff0E7490);boq.setOnClickListener(v->showQuantityEditor(b,false,null));box.addView(boq,new LinearLayout.LayoutParams(-1,dp(46)));}if(!b.drawingUri.isEmpty()){Button plan=smallButton("فتح مخطط المنزل",0xff7A5CB8);plan.setOnClickListener(v->openHousePlan(b.drawingUri));box.addView(plan,new LinearLayout.LayoutParams(-1,dp(46)));}
        TextView photosTitle=text("توثيق تنفيذ الترميم",17,NAVY,true);photosTitle.setPadding(0,dp(14),0,dp(5));box.addView(photosTitle);box.addView(text(photoManager.isConfigured()?"الحفظ داخل: "+photoManager.rootName():"اختر مجلد الصور عند التقاط أول صورة",11,photoManager.isConfigured()?0xff149176:0xffC9851C,true));box.addView(photoStageCard(b,BeneficiaryPhotoManager.BEFORE,0xff0E7490,false));box.addView(photoStageCard(b,BeneficiaryPhotoManager.DURING,0xffC9851C,true));box.addView(photoStageCard(b,BeneficiaryPhotoManager.AFTER,0xff149176,true));
        EditText progress=formInput(box,"نسبة الإنجاز %","من 0 إلى 100",InputType.TYPE_CLASS_NUMBER,false);progress.setText(String.valueOf(b.progressPercent));
        EditText notes=new EditText(this);notes.setHint("ملاحظات متابعة التنفيذ");notes.setText(b.notes);notes.setMinLines(3);notes.setGravity(Gravity.TOP|Gravity.START);notes.setBackground(round(0xffF4F8FB,12,0xffD6E5EB,1));box.addView(notes,new LinearLayout.LayoutParams(-1,dp(95)));
        LinearLayout states=new LinearLayout(this);states.setOrientation(LinearLayout.VERTICAL);box.addView(states);states.addView(statusAction("✓ اكتمل الترميم","completed",0xff149176,b,progress,notes,dialog));states.addView(statusAction("↻ قيد التنفيذ","pending",0xffC9851C,b,progress,notes,dialog));states.addView(statusAction("! بحاجة لمراجعة","review",0xffBD4868,b,progress,notes,dialog));states.addView(statusAction("× تعذر الوصول","unreachable",0xff6B7280,b,progress,notes,dialog));}

    private void saveStudy(AppDatabase.Beneficiary b,EditText address,EditText damage){String value=address.getText().toString().trim();db.updateStudy(b.id,value,damage.getText().toString(),null);if(!value.isEmpty())db.updateClassification(b.id,classifier.classify(value),"دراسة ميدانية");}
    private void markStudyReady(AppDatabase.Beneficiary b,EditText address,EditText damage,AlertDialog dialog){saveStudy(b,address,damage);AppDatabase.Beneficiary fresh=db.beneficiary(b.id);List<String>missing=new ArrayList<>();if(fresh.address.isEmpty())missing.add("العنوان التفصيلي");if(fresh.damageNotes.isEmpty())missing.add("وصف الأضرار");if(db.quantityCount(b.id)==0||db.quantityTotal(b.id)<=0)missing.add("جدول الكميات والمبلغ المحسوب");if(fresh.drawingUri.isEmpty())missing.add("مخطط المنزل");if(db.photoCount(b.id,BeneficiaryPhotoManager.BEFORE)==0)missing.add("صور قبل الترميم");if(!missing.isEmpty()){new AlertDialog.Builder(this).setTitle("الدراسة غير مكتملة").setMessage("أكمل العناصر التالية قبل الاعتماد:\n"+join(missing)).setPositiveButton("حسناً",null).show();return;}db.markStudyReady(b.id);dialog.dismiss();renderActive();toast("أصبحت الدراسة جاهزة للإدراج في دفعة 50");}
    private String quantitySummary(long beneficiaryId){int count=db.quantityCount(beneficiaryId);return count==0?"لم تُدخل كميات بعد":count+" بند محدد من أصل "+quantityCatalog.size()+" بنداً";}
    private String paymentSummary(double total){return "الإجمالي: "+QuantityCatalog.money(total)+" $\nالدفعة الأولى 60%: "+QuantityCatalog.money(total*QuantityCatalog.FIRST_PAYMENT_RATIO)+" $   •   الدفعة الثانية 40%: "+QuantityCatalog.money(total*QuantityCatalog.SECOND_PAYMENT_RATIO)+" $";}
    private double numericQuantity(EditText input){String value=input.getText().toString().trim().replace("٬","").replace("٫",".").replace(',','.');if(value.isEmpty())return 0;try{return Math.max(0,Double.parseDouble(value));}catch(Exception ignored){return 0;}}
    private void showQuantityEditor(AppDatabase.Beneficiary beneficiary,boolean editable,Runnable onSaved){
        Map<Integer,Double>existing=new LinkedHashMap<>();for(AppDatabase.QuantityEntry entry:db.quantities(beneficiary.id))existing.put(entry.itemNo,entry.quantity);
        ScrollView scroll=new ScrollView(this);LinearLayout box=column(dp(14));scroll.addView(box);box.addView(text(editable?"جدول كميات دراسة المنزل":"جدول الكميات المعتمد",20,NAVY,true));
        TextView source=text("37 بنداً من Reference.xlsx — أدخل الكمية فقط، ويُحسب السعر والإجمالي والدفعتان آلياً.",12,MUTED,false);source.setPadding(0,dp(4),0,dp(8));box.addView(source);
        TextView totalView=text("",14,0xff0E7490,true);totalView.setPadding(dp(10),dp(8),dp(10),dp(8));totalView.setBackground(round(0xffEAF7F4,12,0xffB7DED3,1));box.addView(totalView,new LinearLayout.LayoutParams(-1,-2));
        Map<Integer,EditText>fields=new LinkedHashMap<>();Map<Integer,TextView>subtotals=new LinkedHashMap<>();
        Runnable refreshTotal=()->{double total=0;for(QuantityCatalog.Item item:quantityCatalog){EditText field=fields.get(item.number);double quantity=field==null?0:numericQuantity(field);double subtotal=quantity*item.unitPrice;total+=subtotal;TextView subtotalView=subtotals.get(item.number);if(subtotalView!=null)subtotalView.setText("التكلفة: "+QuantityCatalog.money(subtotal)+" $");}totalView.setText(paymentSummary(total));};
        String lastCategory="";for(QuantityCatalog.Item item:quantityCatalog){if(!item.category.equals(lastCategory)){TextView category=text(item.category.trim(),16,NAVY,true);category.setPadding(0,dp(15),0,dp(5));box.addView(category);lastCategory=item.category;}
            LinearLayout card=column(dp(11));card.setBackground(round(Color.WHITE,13,0xffD6E5EB,1));LinearLayout.LayoutParams cardParams=new LinearLayout.LayoutParams(-1,-2);cardParams.setMargins(0,dp(4),0,dp(4));card.setLayoutParams(cardParams);
            TextView name=text(item.number+". "+item.name,14,BLUE,true);name.setOnClickListener(v->showQuantityItem(item));card.addView(name);
            card.addView(text("الوحدة: "+item.unit+"   •   السعر: "+QuantityCatalog.money(item.unitPrice)+" $",11,MUTED,true));
            LinearLayout entryRow=new LinearLayout(this);entryRow.setGravity(Gravity.CENTER_VERTICAL);TextView quantityLabel=text("الكمية",12,TEXT,true);entryRow.addView(quantityLabel,new LinearLayout.LayoutParams(dp(70),dp(48)));
            EditText quantity=new EditText(this);quantity.setSingleLine(true);quantity.setGravity(Gravity.CENTER);quantity.setTextSize(14);quantity.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);Double saved=existing.get(item.number);if(saved!=null&&saved>0)quantity.setText(QuantityCatalog.money(saved));quantity.setEnabled(editable);quantity.setBackground(round(editable?0xffFFF2F6:0xffF0F3F5,10,editable?0xffD879A3:0xffCBD5DB,1));entryRow.addView(quantity,new LinearLayout.LayoutParams(0,dp(46),1));
            TextView subtotal=text("التكلفة: 0 $",11,0xff0E7490,true);subtotal.setGravity(Gravity.CENTER);entryRow.addView(subtotal,new LinearLayout.LayoutParams(dp(125),dp(48)));card.addView(entryRow);box.addView(card);fields.put(item.number,quantity);subtotals.put(item.number,subtotal);
            quantity.addTextChangedListener(new TextWatcher(){@Override public void beforeTextChanged(CharSequence s,int st,int c,int a){}@Override public void onTextChanged(CharSequence s,int st,int before,int count){refreshTotal.run();}@Override public void afterTextChanged(Editable e){}});
        }
        refreshTotal.run();AlertDialog.Builder builder=new AlertDialog.Builder(this).setView(scroll).setNegativeButton(editable?"إلغاء":"إغلاق",null);if(editable)builder.setPositiveButton("حفظ الجدول",null);AlertDialog editor=builder.create();editor.setOnShowListener(v->{editor.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.97),(int)(getResources().getDisplayMetrics().heightPixels*.94));if(editable)editor.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(save->{List<AppDatabase.QuantityEntry>entries=new ArrayList<>();for(QuantityCatalog.Item item:quantityCatalog){double quantity=numericQuantity(fields.get(item.number));if(quantity>0)entries.add(new AppDatabase.QuantityEntry(item.number,quantity,item.unitPrice));}db.saveQuantities(beneficiary.id,entries);editor.dismiss();if(onSaved!=null)onSaved.run();toast(entries.isEmpty()?"تم مسح جدول الكميات":"تم حفظ "+entries.size()+" بنداً واحتساب الإجمالي");});});editor.show();
    }
    private void showQuantityItem(QuantityCatalog.Item item){new AlertDialog.Builder(this).setTitle(item.number+". "+item.name).setMessage("الفئة: "+item.category.trim()+"\nالوحدة: "+item.unit+"\nالسعر: "+QuantityCatalog.money(item.unitPrice)+" $\n\nالوصف:\n"+safe(item.description,"—")+"\n\nسبب التدخل:\n"+safe(item.reason,"—")).setPositiveButton("إغلاق",null).show();}
    private View photoStageCard(AppDatabase.Beneficiary b,String phase,int color){return photoStageCard(b,phase,color,true);}
    private View photoStageCard(AppDatabase.Beneficiary b,String phase,int color,boolean allowCapture){LinearLayout card=column(dp(12));card.setBackground(round(Color.WHITE,14,0xffD6E5EB,1));LinearLayout.LayoutParams cardParams=new LinearLayout.LayoutParams(-1,-2);cardParams.setMargins(0,dp(5),0,dp(5));card.setLayoutParams(cardParams);int count=db.photoCount(b.id,phase);LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);heading.addView(text(BeneficiaryPhotoManager.phaseLabel(phase),15,color,true),new LinearLayout.LayoutParams(0,-2,1));heading.addView(text(count+" صورة",12,MUTED,true));card.addView(heading);LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER);if(allowCapture){Button capture=dialogButton("فتح الكاميرا",color,v->startPhotoCapture(b,phase));actions.addView(capture);}Button open=dialogButton("عرض الصور",NAVY,v->showStagePhotos(b,phase));open.setEnabled(count>0);open.setAlpha(count>0?1f:.4f);actions.addView(open);card.addView(actions);return card;}
    private View statusAction(String label,String status,int color,AppDatabase.Beneficiary b,EditText progress,EditText notes,AlertDialog dialog){Button button=smallButton(label,color);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,dp(4),0,0);button.setLayoutParams(p);button.setOnClickListener(v->{int percent;try{percent=Integer.parseInt(progress.getText().toString().trim());}catch(Exception ignored){percent=0;}percent=Math.max(0,Math.min(100,percent));db.updateVisit(b.id,status,percent,notes.getText().toString());dialog.dismiss();renderActive();Toast.makeText(this,"تم حفظ الحالة ونسبة الإنجاز",Toast.LENGTH_SHORT).show();});return button;}
    private View info(String label,String value){LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(7),0,dp(7));TextView l=text(label,12,MUTED,true);row.addView(l,new LinearLayout.LayoutParams(dp(120),-2));TextView v=text(safe(value,"—"),13,TEXT,false);v.setTextIsSelectable(true);row.addView(v,new LinearLayout.LayoutParams(0,-2,1));return row;}
    private void dial(String phone){try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+phone.replaceAll("[^+0-9]",""))));}catch(Exception e){toast("الاتصال غير متاح على هذا الجهاز");}}

    private void choosePhotoRoot(){Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);startActivityForResult(intent,REQUEST_PHOTO_ROOT);}
    private void chooseHousePlan(AppDatabase.Beneficiary b){pendingPlanBeneficiaryId=b.id;Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("*/*");intent.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/pdf","image/*","application/dxf","application/dwg","application/octet-stream"});intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(intent,REQUEST_HOUSE_PLAN);}
    private void openHousePlan(String value){if(value==null||value.isEmpty()){toast("لم يُرفق مخطط المنزل بعد");return;}try{Uri uri=Uri.parse(value);String type=getContentResolver().getType(uri);Intent open=new Intent(Intent.ACTION_VIEW);open.setDataAndType(uri,type==null?"*/*":type);open.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);open.setClipData(ClipData.newRawUri("مخطط المنزل",uri));startActivity(open);}catch(Exception error){toast("تعذر فتح المخطط؛ تحقق من أن الملف لم يُنقل أو يُحذف");}}
    private void promoteReadyBatch(){int ready=db.studyReadyCount(currentProjectId);if(ready<50){new AlertDialog.Builder(this).setTitle("دفعة المتابعة غير مكتملة").setMessage("عدد الدراسات الجاهزة حالياً: "+ready+" من 50. أكمل اعتماد 50 دراسة قبل إصدار القائمة.").setPositiveButton("حسناً",null).show();return;}String batch="دفعة "+new SimpleDateFormat("yyyy-MM-dd HHmm",Locale.US).format(new Date());new AlertDialog.Builder(this).setTitle("إصدار "+batch).setMessage("سيتم نقل أول 50 دراسة جاهزة إلى مرحلة متابعة التنفيذ. تبقى أي دراسات إضافية للدفعة التالية.").setPositiveButton("اعتماد ونقل",(d,w)->{int moved=db.promoteReadyBatch(currentProjectId,batch);showPage(NAV_ROUTE);toast("تم إصدار القائمة ونقل "+moved+" مستفيداً إلى المتابعة");}).setNegativeButton("إلغاء",null).show();}
    private void startPhotoCapture(AppDatabase.Beneficiary b,String phase){if(!photoManager.isConfigured()){deferredPhotoBeneficiaryId=b.id;deferredPhotoPhase=phase;new AlertDialog.Builder(this).setTitle("اختيار مجلد الصور").setMessage("اختر مجلداً محلياً مرة واحدة. سينشئ التطبيق داخله مجلد المشروع ثم المستفيد ومراحل قبل وأثناء وبعد الترميم.").setPositiveButton("اختيار المجلد",(d,w)->choosePhotoRoot()).setNegativeButton("إلغاء",null).show();return;}try{BeneficiaryPhotoManager.Target target=photoManager.createTarget(currentProject,b,phase);pendingPhotoUri=target.uri;pendingPhotoBeneficiaryId=b.id;pendingPhotoPhase=phase;pendingPhotoFileName=target.fileName;pendingPhotoCapturedAt=target.capturedAt;savePendingPhoto();Intent camera=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);camera.putExtra(MediaStore.EXTRA_OUTPUT,pendingPhotoUri);int grants=Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION;camera.addFlags(grants);camera.setClipData(ClipData.newRawUri("صورة المستفيد",pendingPhotoUri));List<ResolveInfo>handlers=getPackageManager().queryIntentActivities(camera,android.content.pm.PackageManager.MATCH_DEFAULT_ONLY);if(handlers.isEmpty())throw new Exception("لا يوجد تطبيق كاميرا متاح");for(ResolveInfo handler:handlers)grantUriPermission(handler.activityInfo.packageName,pendingPhotoUri,grants);if(beneficiaryDialog!=null)beneficiaryDialog.dismiss();startActivityForResult(camera,REQUEST_CAPTURE_PHOTO);}catch(Exception error){if(pendingPhotoUri!=null)photoManager.delete(pendingPhotoUri);clearPendingPhoto();new AlertDialog.Builder(this).setTitle("تعذر بدء التصوير").setMessage(error.getMessage()).setPositiveButton("حسناً",null).show();}}
    private void handlePhotoCapture(int result){Uri completed=pendingPhotoUri;long beneficiaryId=pendingPhotoBeneficiaryId;String phase=pendingPhotoPhase,fileName=pendingPhotoFileName;long capturedAt=pendingPhotoCapturedAt;if(completed==null)return;try{revokeUriPermission(completed,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);}catch(Exception ignored){}if(result!=RESULT_OK){photoManager.delete(completed);clearPendingPhoto();toast("أُلغي التصوير ولم يُحفظ ملف فارغ");AppDatabase.Beneficiary b=db.beneficiary(beneficiaryId);if(b!=null)showBeneficiary(b);return;}try{if(!photoHasData(completed))throw new Exception("لم تُكتب بيانات الصورة بواسطة تطبيق الكاميرا");long photoId=db.addPhoto(beneficiaryId,phase,completed.toString(),fileName,capturedAt,"");clearPendingPhoto();AppDatabase.Beneficiary b=db.beneficiary(beneficiaryId);toast("حُفظت الصورة في «"+BeneficiaryPhotoManager.phaseLabel(phase)+"»");if(b!=null)promptPhotoNote(photoId,b);}catch(Exception error){photoManager.delete(completed);clearPendingPhoto();new AlertDialog.Builder(this).setTitle("تعذر تسجيل الصورة").setMessage(error.getMessage()).setPositiveButton("حسناً",null).show();}}
    private boolean photoHasData(Uri uri){try(android.content.res.AssetFileDescriptor descriptor=getContentResolver().openAssetFileDescriptor(uri,"r")){return descriptor!=null&&descriptor.getLength()!=0;}catch(Exception error){return false;}}
    private void promptPhotoNote(long photoId,AppDatabase.Beneficiary b){EditText note=new EditText(this);note.setHint("مثال: إزالة الأنقاض، تنفيذ القميص، استلام المرحلة...");note.setMinLines(3);note.setGravity(Gravity.TOP|Gravity.START);note.setPadding(dp(14),dp(10),dp(14),dp(10));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("ملاحظة على الصورة").setMessage("اختياري — تساعد الملاحظة في متابعة سير العمل.").setView(note).setPositiveButton("حفظ",(d,w)->db.updatePhotoNote(photoId,note.getText().toString().trim())).setNegativeButton("لاحقاً",null).create();dialog.setOnDismissListener(v->{AppDatabase.Beneficiary fresh=db.beneficiary(b.id);if(fresh!=null&&!isFinishing())showBeneficiary(fresh);});dialog.show();}

    private void showStagePhotos(AppDatabase.Beneficiary b,String phase){List<AppDatabase.Photo>photos=db.photos(b.id,phase);ScrollView scroll=new ScrollView(this);LinearLayout box=column(dp(14));scroll.addView(box);box.addView(text(BeneficiaryPhotoManager.phaseLabel(phase)+" — "+photos.size()+" صورة",19,NAVY,true));SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd  HH:mm",Locale.US);for(AppDatabase.Photo photo:photos){LinearLayout card=new LinearLayout(this);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(8),dp(8),dp(8),dp(8));card.setBackground(round(Color.WHITE,12,0xffD6E5EB,1));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(5),0,dp(5));card.setLayoutParams(cp);ImageView preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.CENTER_CROP);preview.setBackgroundColor(0xffE7EEF2);card.addView(preview,new LinearLayout.LayoutParams(dp(128),dp(96)));loadThumbnail(preview,Uri.parse(photo.uri));LinearLayout details=column(dp(9));details.addView(text(format.format(new Date(photo.capturedAt)),12,NAVY,true));details.addView(text(safe(photo.note,"دون ملاحظة"),11,MUTED,false));Button open=smallButton("فتح الصورة",0xff0E7490);open.setOnClickListener(v->openPhoto(photo));LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(42));op.setMargins(0,dp(6),0,0);details.addView(open,op);card.addView(details,new LinearLayout.LayoutParams(0,-2,1));box.addView(card);}AlertDialog dialog=new AlertDialog.Builder(this).setView(scroll).setPositiveButton("إغلاق",null).create();dialog.setOnShowListener(v->dialog.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.96),(int)(getResources().getDisplayMetrics().heightPixels*.90)));dialog.show();}
    private void openPhoto(AppDatabase.Photo photo){try{Uri uri=Uri.parse(photo.uri);Intent view=new Intent(Intent.ACTION_VIEW);view.setDataAndType(uri,"image/jpeg");view.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);view.setClipData(ClipData.newRawUri("صورة المستفيد",uri));startActivity(view);}catch(Exception error){toast("تعذر فتح الصورة؛ تحقق من أن المجلد لم يُنقل أو يُحذف");}}
    private void loadThumbnail(ImageView target,Uri uri){worker.execute(()->{try{Bitmap image=decodeThumbnail(uri,520);runOnUiThread(()->{if(image!=null&&!isFinishing())target.setImageBitmap(image);});}catch(Exception ignored){runOnUiThread(()->target.setImageResource(android.R.drawable.ic_menu_report_image));}});}
    private Bitmap decodeThumbnail(Uri uri,int targetSize)throws Exception{BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;try(InputStream input=getContentResolver().openInputStream(uri)){if(input==null)throw new Exception("تعذر فتح الصورة");BitmapFactory.decodeStream(input,null,bounds);}int sample=1;while(bounds.outWidth/sample>targetSize*2||bounds.outHeight/sample>targetSize*2)sample*=2;BitmapFactory.Options options=new BitmapFactory.Options();options.inSampleSize=Math.max(1,sample);try(InputStream input=getContentResolver().openInputStream(uri)){if(input==null)throw new Exception("تعذر فتح الصورة");return BitmapFactory.decodeStream(input,null,options);}}
    private void savePendingPhoto(){getPreferences(MODE_PRIVATE).edit().putString("pending_photo_uri",pendingPhotoUri==null?"":pendingPhotoUri.toString()).putLong("pending_photo_beneficiary",pendingPhotoBeneficiaryId).putString("pending_photo_phase",pendingPhotoPhase).putString("pending_photo_file",pendingPhotoFileName).putLong("pending_photo_time",pendingPhotoCapturedAt).apply();}
    private void restorePendingPhoto(){String saved=getPreferences(MODE_PRIVATE).getString("pending_photo_uri","");if(saved!=null&&!saved.isEmpty())pendingPhotoUri=Uri.parse(saved);pendingPhotoBeneficiaryId=getPreferences(MODE_PRIVATE).getLong("pending_photo_beneficiary",0);pendingPhotoPhase=getPreferences(MODE_PRIVATE).getString("pending_photo_phase","");pendingPhotoFileName=getPreferences(MODE_PRIVATE).getString("pending_photo_file","");pendingPhotoCapturedAt=getPreferences(MODE_PRIVATE).getLong("pending_photo_time",0);}
    private void clearPendingPhoto(){pendingPhotoUri=null;pendingPhotoBeneficiaryId=0;pendingPhotoPhase="";pendingPhotoFileName="";pendingPhotoCapturedAt=0;getPreferences(MODE_PRIVATE).edit().remove("pending_photo_uri").remove("pending_photo_beneficiary").remove("pending_photo_phase").remove("pending_photo_file").remove("pending_photo_time").apply();}

    private void showGuide(){ScrollView scroll=new ScrollView(this);content.addView(scroll,new FrameLayout.LayoutParams(-1,-1));LinearLayout box=column(dp(16));scroll.addView(box);box.addView(text("دليل قطاعات وشوارع مخيم اليرموك",21,NAVY,true));TextView sub=text("المخطط التنظيمي الكامل والمخطط المقسّم إلى 7 صفحات مضمّنان داخل التطبيق. اضغط على دائرة القطاع أو أحد أزرار الفتح، ثم كبّر بإصبعين واسحب المخطط.",12,MUTED,false);sub.setPadding(0,dp(4),0,dp(12));box.addView(sub);
        box.addView(action("فتح المخطط التنظيمي الكامل","اختر PDF داخل التطبيق أو ملف DWG في عارض CAD",BLUE,v->showMapOptions(false,0,"المخطط التنظيمي لمخيم اليرموك")));
        box.addView(action("فتح المخطط المقسّم كاملاً","اختر PDF بسبع صفحات أو ملف DXF في عارض CAD",0xff149176,v->showMapOptions(true,0,"مخططات قطاعات مخيم اليرموك")));
        Spinner sector=new Spinner(this);SectorMapView map=new SectorMapView(this);map.setBackground(round(0xffF4FAFC,18,0xffD6E6EC,1));map.setOnSectorClickListener((index,name)->{sector.setSelection(index);showMapOptions(true,SECTOR_PDF_PAGES[index],"مخطط قطاع "+name);});LinearLayout.LayoutParams mapParams=new LinearLayout.LayoutParams(-1,dp(350));mapParams.setMargins(0,dp(10),0,0);box.addView(map,mapParams);
        TextView mapHint=text("اضغط على دائرة القطاع لفتح مخططه الحقيقي مباشرة",11,0xff0E7490,true);mapHint.setGravity(Gravity.CENTER);mapHint.setPadding(0,dp(7),0,0);box.addView(mapHint);
        TextView choose=text("اختر القطاع",15,NAVY,true);choose.setPadding(0,dp(18),0,dp(6));box.addView(choose);ArrayAdapter<String>adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,AddressClassifier.SECTOR_ORDER);sector.setAdapter(adapter);sector.setBackground(round(Color.WHITE,12,0xffD6E5EB,1));box.addView(sector,new LinearLayout.LayoutParams(-1,dp(50)));
        Button openSector=smallButton("فتح مخطط القطاع المحدد",0xff0E7490);LinearLayout.LayoutParams openParams=new LinearLayout.LayoutParams(-1,dp(50));openParams.setMargins(0,dp(8),0,dp(4));openSector.setLayoutParams(openParams);openSector.setOnClickListener(v->{int pos=sector.getSelectedItemPosition();String name=AddressClassifier.SECTOR_ORDER.get(pos);showMapOptions(true,SECTOR_PDF_PAGES[pos],"مخطط قطاع "+name);});box.addView(openSector);LinearLayout streets=column(dp(8));box.addView(streets,new LinearLayout.LayoutParams(-1,-2));
        sector.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){@Override public void onNothingSelected(AdapterView<?>p){}@Override public void onItemSelected(AdapterView<?>p,View v,int pos,long id){map.setSelectedSector(pos);streets.removeAllViews();String name=AddressClassifier.SECTOR_ORDER.get(pos);List<String>items=classifier.getReference().get(name);TextView count=text(name+" — "+items.size()+" شارعاً/معلماً",15,0xff0E7490,true);count.setPadding(0,dp(12),0,dp(6));streets.addView(count);for(int i=0;i<items.size();i++){String street=items.get(i);TextView line=text((i+1)+". "+street,13,TEXT,false);line.setPadding(dp(10),dp(9),dp(10),dp(9));line.setBackground(round(i%2==0?0xffEAF4F7:Color.WHITE,8,0,0));streets.addView(line,new LinearLayout.LayoutParams(-1,-2));}}});}

    private void showMapOptions(boolean sectorMap,int pdfPage,String title){String[]options={"عرض PDF داخل التطبيق","فتح ملف CAD "+(sectorMap?"DXF":"DWG")};new AlertDialog.Builder(this).setTitle(title).setMessage("اختر طريقة العرض. يحتاج خيار CAD إلى تطبيق يدعم "+(sectorMap?"DXF":"DWG")+" على الهاتف.").setItems(options,(dialog,which)->{if(which==0)PdfMapViewer.show(this,sectorMap?R.raw.yarmouk_sector_maps:R.raw.yarmouk_camp_map,pdfPage,title);else openEmbeddedCad(sectorMap);}).setNegativeButton("إلغاء",null).show();}
    private void openEmbeddedCad(boolean sectorMap){String asset=sectorMap?"yarmouk_sector_maps.dxf":"yarmouk_camp_map.dwg";String outputName=sectorMap?"Yarmouk_Sector_Maps.dxf":"Yarmouk_Camp_Map.dwg";String mime=sectorMap?"application/dxf":"application/vnd.dwg";try{File folder=new File(getCacheDir(),"embedded_cad");if(!folder.exists()&&!folder.mkdirs())throw new Exception("تعذر تجهيز مجلد CAD");File output=new File(folder,outputName);try(InputStream input=getAssets().open(asset);FileOutputStream stream=new FileOutputStream(output,false)){byte[]buffer=new byte[32768];int count;while((count=input.read(buffer))!=-1)stream.write(buffer,0,count);}Uri uri=CadFileProvider.uriFor(this,output);Intent open=new Intent(Intent.ACTION_VIEW);open.setDataAndType(uri,mime);open.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);open.setClipData(ClipData.newRawUri("مخطط CAD",uri));startActivity(Intent.createChooser(open,"فتح المخطط باستخدام"));}catch(Exception error){new AlertDialog.Builder(this).setTitle("تعذر فتح ملف CAD").setMessage("ثبّت تطبيقاً يدعم "+(sectorMap?"DXF":"DWG")+" ثم أعد المحاولة. يمكنك دائماً اختيار عرض PDF داخل التطبيق.\n\n"+safe(error.getMessage(),"لا يوجد عارض متوافق")).setPositiveButton("حسناً",null).show();}}

    private void showSettings(){ScrollView scroll=new ScrollView(this);content.addView(scroll,new FrameLayout.LayoutParams(-1,-1));LinearLayout box=column(dp(16));scroll.addView(box);box.addView(text("الإعدادات وحماية البيانات",21,NAVY,true));box.addView(setting("دليل استخدام التطبيق","شرح تفاعلي داخل التطبيق",0xff7A5CB8,v->showUserGuide()));box.addView(setting("دليل الاستخدام PDF","نسخة عربية مرفقة تعمل دون إنترنت وقابلة للطباعة",0xff0E7490,v->PdfMapViewer.show(this,R.raw.user_guide_ar,0,"دليل استخدام التطبيق")));box.addView(setting("مجلد صور المستفيدين",photoManager.isConfigured()?"المجلد الحالي: "+photoManager.rootName():"لم يتم اختياره — اضغط لتحديد مجلد محلي",0xff0E7490,v->choosePhotoRoot()));box.addView(setting("المشروع الحالي",currentProject,BLUE,v->newProject()));box.addView(setting("إنشاء مشروع أو قائمة جديدة","يحفظ كل مشروع وبياناته بصورة مستقلة",BLUE,v->newProject()));box.addView(setting("نسخة احتياطية JSON","تصدير الدراسات والمتابعة وجدول الكميات وفهرس الصور",0xff149176,v->createBackup()));box.addView(setting("استيراد قائمة أو نسخة احتياطية","Excel أو CSV أو JSON من ذاكرة الهاتف",0xff0E7490,v->chooseImport()));box.addView(setting("حذف بيانات المشروع الحالي","لا يحذف مجلدات الصور ولا المشاريع الأخرى",0xffBD4868,v->confirmClear()));
        LinearLayout about=column(dp(16));about.setBackground(round(Color.WHITE,16,0xffD6E5EB,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(18),0,0);about.setLayoutParams(p);about.addView(text("حول التطبيق",16,NAVY,true));about.addView(text("Yarmouk Camp Shelter — Android Field Edition\nإصدار "+APP_VERSION+" • يعمل دون إنترنت\n\n"+DESIGNER_CREDIT+"\n\n"+ACKNOWLEDGEMENT+".\n\nمرجع القطاعات: ملف الشوارع + DXF + المخططان PDF\nالبيانات والصور تبقى محلياً على الجهاز.",12,MUTED,false));box.addView(about);}
    private void showUserGuide(){ScrollView scroll=new ScrollView(this);LinearLayout box=column(dp(18));scroll.addView(box);box.addView(text("دليل استخدام تطبيق مخيم اليرموك",21,NAVY,true));TextView intro=text("التطبيق يعمل دون إنترنت، ويحفظ كل مشروع وزياراته محلياً على الهاتف.",13,MUTED,false);intro.setPadding(0,dp(5),0,dp(10));box.addView(intro);Button pdfGuide=smallButton("فتح نسخة الدليل PDF",0xff0E7490);pdfGuide.setOnClickListener(v->PdfMapViewer.show(this,R.raw.user_guide_ar,0,"دليل استخدام التطبيق"));box.addView(pdfGuide,new LinearLayout.LayoutParams(-1,dp(48)));
        guideStep(box,"1","إنشاء المشروع","أنشئ مشروعاً مستقلاً، ثم ابدأ من تبويب «الدراسات» من دون الحاجة إلى قائمة مسبقة.");
        guideStep(box,"2","فتح دراسة مستفيد","أضف اسم المستفيد ورقم الهاتف والبيانات الأولية عند زيارة المنزل.");
        guideStep(box,"3","توثيق الأضرار","اختر مجلد الصور مرة واحدة، ثم صوّر المنزل والأضرار ضمن مرحلة «قبل الترميم»؛ يحفظ التطبيق الصور داخل مجلد المستفيد تلقائياً.");
        guideStep(box,"4","استكمال الدراسة","اكتب العنوان التفصيلي ووصف الأضرار، ثم افتح جدول الكميات المرجعي واختر الكميات المطلوبة من البنود الـ37. يحسب التطبيق الإجمالي والدفعتين 60% و40% آلياً، ثم اربط مخطط المنزل بصيغة PDF أو DXF أو DWG أو صورة.");
        guideStep(box,"5","اعتماد الدراسة","بعد اكتمال البيانات والصور والمخطط، اضغط «اعتماد الدراسة» لتصبح جاهزة للإدراج في قائمة التنفيذ.");
        guideStep(box,"6","إصدار دفعة 50","عندما تصبح 50 دراسة جاهزة، اضغط «دفعة 50» لنقلها معاً إلى تبويب «المتابعة».");
        guideStep(box,"7","متابعة التنفيذ","افتح المستفيد من قائمة المتابعة، وسجّل نسبة الإنجاز من 0 إلى 100، وصوّر مرحلة «أثناء الترميم»، ثم مرحلة «بعد الترميم» عند الإنجاز وسجل الحالة النهائية.");
        guideStep(box,"8","استيراد قائمة متابعة","يمكن استيراد XLSX أو CSV أو JSON كقائمة متابعة جاهزة. يعالج هذا الإصدار خطأ XMLReader؛ حوّل ملفات XLS القديمة إلى XLSX أولاً.");
        guideStep(box,"9","المخططات والشوارع","عند فتح أي مخطط اختر PDF داخل التطبيق، أو CAD لفتح DWG/DXF في تطبيق خارجي متوافق. يدعم عارض PDF التكبير والسحب دون إنترنت.");
        guideStep(box,"10","حماية البيانات","احفظ نسخة JSON دورياً وانسخ مجلد الصور أيضاً؛ ملف JSON يتضمن الدراسات والمتابعة وجداول الكميات وفهرس الصور، أما ملفات الصور نفسها فتبقى في مجلدها.");
        AlertDialog dialog=new AlertDialog.Builder(this).setView(scroll).setPositiveButton("إغلاق",null).create();dialog.setOnShowListener(v->dialog.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.96),(int)(getResources().getDisplayMetrics().heightPixels*.90)));dialog.show();}
    private void guideStep(LinearLayout box,String number,String title,String body){LinearLayout card=column(dp(14));card.setBackground(round(Color.WHITE,15,0xffD6E5EB,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));card.setLayoutParams(p);card.addView(text(number+". "+title,15,0xff0E7490,true));TextView detail=text(body,12,TEXT,false);detail.setPadding(0,dp(5),0,0);card.addView(detail);box.addView(card);}
    private View setting(String title,String sub,int color,View.OnClickListener click){LinearLayout card=column(dp(14));card.setMinimumHeight(dp(88));card.setBackground(round(Color.WHITE,15,0xffD6E5EB,1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(5),0,dp(5));card.setLayoutParams(p);card.addView(text(title,15,color,true));card.addView(text(sub,11,MUTED,false));card.setOnClickListener(click);return card;}
    private void newProject(){EditText input=new EditText(this);input.setHint("مثال: قائمة آب 2026");input.setSingleLine(true);input.setPadding(dp(16),0,dp(16),0);new AlertDialog.Builder(this).setTitle("مشروع جديد").setMessage("سيظهر له قسم مستقل داخل التطبيق.").setView(input).setPositiveButton("إنشاء",(d,w)->{String name=input.getText().toString().trim();if(name.isEmpty()){toast("اكتب اسم المشروع");return;}currentProject=name;currentProjectId=db.ensureProject(name);getPreferences(MODE_PRIVATE).edit().putString("current_project",name).apply();refreshProjects();renderActive();}).setNegativeButton("إلغاء",null).show();}
    private void confirmClear(){new AlertDialog.Builder(this).setTitle("حذف بيانات المشروع؟").setMessage("سيتم حذف جميع المستفيدين وحالات الزيارة وفهرس الصور من «"+currentProject+"». لن تُحذف ملفات الصور من المجلد المختار. يفضّل أخذ نسخة احتياطية أولاً.").setPositiveButton("حذف",(d,w)->{db.deleteProjectData(currentProjectId);renderActive();toast("تم حذف بيانات المشروع وبقيت ملفات الصور في مجلدها");}).setNegativeButton("إلغاء",null).show();}

    private void chooseImport(){Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("*/*");intent.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/csv","application/json","text/plain"});startActivityForResult(intent,REQUEST_IMPORT);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==REQUEST_CAPTURE_PHOTO){handlePhotoCapture(result);return;}if(result!=RESULT_OK){if(request==REQUEST_PHOTO_ROOT){deferredPhotoBeneficiaryId=0;deferredPhotoPhase="";}if(request==REQUEST_HOUSE_PLAN)pendingPlanBeneficiaryId=0;return;}if(data==null||data.getData()==null)return;Uri uri=data.getData();if(request==REQUEST_IMPORT)importUri(uri);else if(request==REQUEST_BACKUP)writeBackup(uri);else if(request==REQUEST_HOUSE_PLAN){long beneficiaryId=pendingPlanBeneficiaryId;pendingPlanBeneficiaryId=0;try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}db.setDrawingUri(beneficiaryId,uri.toString());if(beneficiaryDialog!=null)beneficiaryDialog.dismiss();AppDatabase.Beneficiary fresh=db.beneficiary(beneficiaryId);if(fresh!=null)showBeneficiary(fresh);toast("تم ربط مخطط المنزل بالدراسة");}else if(request==REQUEST_PHOTO_ROOT){try{photoManager.setRoot(uri,data.getFlags());toast("تم اعتماد مجلد الصور: "+photoManager.rootName());long beneficiaryId=deferredPhotoBeneficiaryId;String phase=deferredPhotoPhase;deferredPhotoBeneficiaryId=0;deferredPhotoPhase="";AppDatabase.Beneficiary b=db.beneficiary(beneficiaryId);if(b!=null&&!phase.isEmpty())startPhotoCapture(b,phase);else renderActive();}catch(Exception error){new AlertDialog.Builder(this).setTitle("تعذر اعتماد المجلد").setMessage(error.getMessage()).setPositiveButton("حسناً",null).show();}}}
    private void importUri(Uri uri){ProgressDialog progress=new ProgressDialog(this);progress.setMessage("جارٍ قراءة الملف وتصنيف العناوين…");progress.setCancelable(false);progress.show();worker.execute(()->{try{SpreadsheetImporter.Result result=SpreadsheetImporter.read(this,uri);int inferred=SpreadsheetImporter.enrichAddresses(result.rows,classifier);if(inferred>0)result.warnings.add("تم استكمال "+inferred+" عنواناً من سجلات مرتبطة داخل الملف؛ راجع المصدر قبل الزيارة.");for(AppDatabase.Beneficiary b:result.rows){AddressClassifier.Match m=classifier.classify(b.address);b.sector=m.sector;b.street=m.street;b.matchStatus=(b.addressSource.isEmpty()?"":"مستكمل من "+b.addressSource+" — تحقق سريع | ")+m.review;b.confidence=m.confidence;b.sectorOrder=m.sectorIndex;b.routeOrder=m.routeIndex;b.streetOrder=m.streetIndex;b.alleyOrder=m.alleyIndex;if(!result.backup){b.workflowStage="followup";b.studyStatus="approved";b.followupBatch="قائمة مستوردة";b.approvedAt=System.currentTimeMillis();}}runOnUiThread(()->{progress.dismiss();confirmImport(result);});}catch(Exception e){runOnUiThread(()->{progress.dismiss();new AlertDialog.Builder(this).setTitle("تعذر استيراد الملف").setMessage(friendlyImportError(e)).setPositiveButton("حسناً",null).show();});}});}
    private String friendlyImportError(Throwable error){String raw=error.getMessage()==null?error.toString():error.getMessage();String lower=raw.toLowerCase(Locale.ROOT);if(lower.contains("xmlreader")||lower.contains("org.xml.sax.driver"))return "تعذر تشغيل قارئ Excel على هذا الجهاز. يعالج هذا الإصدار مشكلة قارئ XML؛ إذا ظهرت مرة أخرى أغلق التطبيق وأعد فتحه.";if(lower.contains("zip")||lower.contains("central directory"))return "الملف ليس مصنف Excel XLSX سليماً أو قد يكون تالفاً. افتحه في Excel واحفظه مرة أخرى بصيغة XLSX.";return "لم يتمكن التطبيق من قراءة الملف. تأكد من أنه XLSX أو CSV أو JSON وأنه ليس محمياً بكلمة مرور.\n\nالتفصيل التقني: "+raw;}
    private void confirmImport(SpreadsheetImporter.Result result){if(result.rows.isEmpty()){new AlertDialog.Builder(this).setTitle("لا توجد سجلات").setMessage(result.warnings.isEmpty()?"لم يُعثر على بيانات قابلة للاستيراد.":join(result.warnings)).setPositiveButton("حسناً",null).show();return;}int review=0;for(AppDatabase.Beneficiary b:result.rows)if(b.matchStatus.contains("مراجعة"))review++;String message=(result.backup?"تم التحقق من نسخة احتياطية تضم ":"تم العثور على ")+result.rows.size()+" مستفيداً\nبحاجة لمراجعة العنوان: "+review;if(result.backup)message+="\nسيُستعاد جدول الكميات ومراحل الدراسة والمتابعة.";if(!result.warnings.isEmpty())message+="\n\nملاحظات الربط:\n"+join(result.warnings);message+="\n\nاختر استبدال بيانات المشروع أو الإضافة إليها.";
        new AlertDialog.Builder(this).setTitle(result.backup?"النسخة الاحتياطية جاهزة للاستعادة":"القائمة جاهزة للاستيراد").setMessage(message).setPositiveButton("استبدال",(d,w)->saveImport(result,true)).setNeutralButton("إضافة",(d,w)->saveImport(result,false)).setNegativeButton("إلغاء",null).show();}
    private void saveImport(SpreadsheetImporter.Result result,boolean replace){db.importBeneficiaries(currentProjectId,result.rows,replace);toast("تم حفظ "+result.rows.size()+" مستفيداً وترتيب العناوين");showPage(NAV_HOME);}

    private void createBackup(){try{pendingBackup=db.backup(currentProjectId,currentProject).toString(2);Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("application/json");String date=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());intent.putExtra(Intent.EXTRA_TITLE,"Yarmouk_"+safeFile(currentProject)+"_"+date+".json");startActivityForResult(intent,REQUEST_BACKUP);}catch(Exception e){fatal("تعذر تجهيز النسخة الاحتياطية",e);}}
    private void writeBackup(Uri uri){try(OutputStream out=getContentResolver().openOutputStream(uri)){if(out==null)throw new Exception("تعذر فتح ملف الحفظ");out.write(pendingBackup.getBytes(StandardCharsets.UTF_8));toast("تم حفظ النسخة الاحتياطية بنجاح");}catch(Exception e){fatal("تعذر حفظ النسخة الاحتياطية",e);}finally{pendingBackup=null;}}
    private void printRoute(){List<AppDatabase.Beneficiary>rows=db.listStage(currentProjectId,"","followup","all");if(rows.isEmpty()){toast("لا توجد قائمة متابعة للطباعة");return;}PrintManager manager=(PrintManager)getSystemService(Context.PRINT_SERVICE);PrintAttributes attrs=new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4.asLandscape()).setColorMode(PrintAttributes.COLOR_MODE_COLOR).setMinMargins(PrintAttributes.Margins.NO_MARGINS).build();manager.print("Yarmouk_Field_"+safeFile(currentProject),new PrintRouteAdapter(this,currentProject,PRINT_CREDIT,rows),attrs);}

    private TextView text(String value,int sp,int color,boolean bold){TextView v=new TextView(this);v.setText(value);v.setTextSize(sp);v.setTextColor(color);v.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);if(bold)v.setTypeface(Typeface.create("sans",Typeface.BOLD));v.setLineSpacing(0,1.12f);return v;}
    private LinearLayout column(int padding){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(padding,padding,padding,padding);return v;}
    private Button smallButton(String value,int color){Button b=new Button(this);b.setText(value);b.setTextColor(Color.WHITE);b.setTextSize(12);b.setTypeface(null,Typeface.BOLD);b.setAllCaps(false);b.setPadding(dp(12),0,dp(12),0);b.setBackground(round(color,12,0,0));return b;}
    private Button dialogButton(String value,int color,View.OnClickListener click){Button b=smallButton(value,color);b.setOnClickListener(click);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);p.setMargins(dp(3),dp(6),dp(3),dp(6));b.setLayoutParams(p);return b;}
    private GradientDrawable round(int color,int radius,int stroke,int strokeWidth){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(strokeWidth>0)d.setStroke(dp(strokeWidth),stroke);return d;}
    private int dp(int value){return (int)(value*getResources().getDisplayMetrics().density+.5f);}
    private int computeResource(String name,String type){return getResources().getIdentifier(name,type,getPackageName());}
    private int statusColor(String status){if("completed".equals(status))return 0xff149176;if("review".equals(status))return 0xffBD4868;if("unreachable".equals(status))return 0xff6B7280;return 0xffC9851C;}
    private String statusLabel(String status){if("completed".equals(status))return "تمت الزيارة";if("review".equals(status))return "بحاجة لمراجعة";if("unreachable".equals(status))return "تعذر الوصول";return "بانتظار الزيارة";}
    private int studyStatusColor(String status){return "ready".equals(status)?0xff149176:0xff7A5CB8;}
    private String studyStatusLabel(String status){return "ready".equals(status)?"جاهزة لدفعة المتابعة":"قيد استكمال الدراسة";}
    private static String safe(String value,String fallback){return value==null||value.trim().isEmpty()?fallback:value.trim();}
    private static String safeFile(String value){return value.replaceAll("[^0-9a-zA-Z\\u0600-\\u06FF._-]+","_");}
    private static String shortStreet(String value){String[]parts=value.split("[/()\\-–—]");return parts.length==0?value:parts[0].trim();}
    private static String join(List<String>values){StringBuilder b=new StringBuilder();for(String v:values)b.append("• ").append(v).append('\n');return b.toString();}
    private void toast(String value){Toast.makeText(this,value,Toast.LENGTH_LONG).show();}
    private void fatal(String title,Exception e){new AlertDialog.Builder(this).setTitle(title).setMessage(e.getMessage()==null?e.toString():e.getMessage()).setPositiveButton("إغلاق",(d,w)->finish()).show();}
}
